### ISSUE TITLE
TF apply crash with rancher2_auth_config_activedirectory

### ISSUE THREAD

**Issue by yvespp** [rancher/terraform-provider-rancher2-archive#14]
Log of the crash:
```
...
Error: Error applying plan:

1 error(s) occurred:

* module.rancher_cluster.rancher2_auth_config_activedirectory.activedirectory: 1 error(s) occurred:

* rancher2_auth_config_activedirectory.activedirectory: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


panic: runtime error: invalid memory address or nil pointer dereference
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9d1e32]
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: goroutine 83 [running]:
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: github.com/rancher/terraform-provider-rancher2/vendor/github.com/rancher/norman/clientbase.(*APIOperations).DoByID(0x0, 0xcb0079, 0xa, 0xcb3dfb, 0xf, 0xb1eba0, 0xc0003c9770, 0xc00009c9c6, 0x1350350)
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /go/src/github.com/rancher/terraform-provider-rancher2/vendor/github.com/rancher/norman/clientbase/ops.go:245 +0x72
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: github.com/rancher/terraform-provider-rancher2/vendor/github.com/rancher/types/client/management/v3.(*AuthConfigClient).ByID(0xc0001633d0, 0xcb3dfb, 0xf, 0x0, 0x8, 0x40)
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /go/src/github.com/rancher/terraform-provider-rancher2/vendor/github.com/rancher/types/client/management/v3/zz_generated_auth_config.go:101 +0x89
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: github.com/rancher/terraform-provider-rancher2/rancher2.resourceRancher2AuthConfigActiveDirectoryCreate(0xc00022bb90, 0xc84c60, 0xc000394900, 0x24, 0x1379540)
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /go/src/github.com/rancher/terraform-provider-rancher2/rancher2/resource_rancher2_auth_config_activedirectory.go:440 +0xa5
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: github.com/rancher/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0004882a0, 0xc00027cfa0, 0xc0001539a0, 0xc84c60, 0xc000394900, 0x40d601, 0xc000054b80, 0x4c1a3c)
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /go/src/github.com/rancher/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:193 +0x358
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: github.com/rancher/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00022b110, 0xc00027cf50, 0xc00027cfa0, 0xc0001539a0, 0xc000272700, 0x18, 0x7fb7996fad80)
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /go/src/github.com/rancher/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:259 +0x9c
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: github.com/rancher/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc000152e60, 0xc000153560, 0xc00049bff0, 0x0, 0x0)
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /go/src/github.com/rancher/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: reflect.Value.call(0xc00012c360, 0xc000162fa8, 0x13, 0xcaa36c, 0x4, 0xc000054f18, 0x3, 0x3, 0xc000134400, 0xc000241a00, ...)
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /usr/local/go/src/reflect/value.go:447 +0x449
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: reflect.Value.Call(0xc00012c360, 0xc000162fa8, 0x13, 0xc000045718, 0x3, 0x3, 0x0, 0xc000489c20, 0x0)
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /usr/local/go/src/reflect/value.go:308 +0xa4
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: net/rpc.(*service).call(0xc000169cc0, 0xc00027ce10, 0xc000155700, 0xc000155710, 0xc000156980, 0xc0001533c0, 0xb1c660, 0xc000153560, 0x16, 0xb1c6a0, ...)
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2: created by net/rpc.(*Server).ServeCodec
2018-12-03T18:35:03.201+0100 [DEBUG] plugin.terraform-provider-rancher2:        /usr/local/go/src/net/rpc/server.go:481 +0x47e
2018/12/03 18:35:03 [TRACE] root.rancher_cluster: eval: *terraform.EvalWriteState
2018/12/03 18:35:03 [TRACE] root.rancher_cluster: eval: *terraform.EvalApplyProvisioners
2018/12/03 18:35:03 [TRACE] root.rancher_cluster: eval: *terraform.EvalIf
2018/12/03 18:35:03 [TRACE] root.rancher_cluster: eval: *terraform.EvalWriteState
2018/12/03 18:35:03 [TRACE] root.rancher_cluster: eval: *terraform.EvalWriteDiff
2018-12-03T18:35:03.203+0100 [DEBUG] plugin: plugin process exited: path=/home/yvespp/.terraform.d/plugins/terraform-provider-rancher2
2018/12/03 18:35:03 [TRACE] root.rancher_cluster: eval: *terraform.EvalApplyPost
2018/12/03 18:35:03 [ERROR] root.rancher_cluster: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* rancher2_auth_config_activedirectory.activedirectory: unexpected EOF
2018/12/03 18:35:03 [ERROR] root.rancher_cluster: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* rancher2_auth_config_activedirectory.activedirectory: unexpected EOF
2018/12/03 18:35:03 [TRACE] [walkApply] Exiting eval tree: module.rancher_cluster.rancher2_auth_config_activedirectory.activedirectory
2018/12/03 18:35:03 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/12/03 18:35:03 [TRACE] dag/walk: upstream errored, not walking "module.rancher_cluster.provider.rancher2 (close)"
2018/12/03 18:35:03 [TRACE] dag/walk: upstream errored, not walking "root"
2018/12/03 18:35:03 [TRACE] Preserving existing state lineage "ab05d14a-7af8-d317-ac81-68470910fb63"
2018/12/03 18:35:03 [TRACE] Preserving existing state lineage "ab05d14a-7af8-d317-ac81-68470910fb63"
2018/12/03 18:35:03 [TRACE] Preserving existing state lineage "ab05d14a-7af8-d317-ac81-68470910fb63"
2018/12/03 18:35:03 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-12-03T18:35:03.217+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-12-03T18:35:03.217+0100 [DEBUG] plugin.terraform-provider-vsphere_v1.9.0_x4: 2018/12/03 18:35:03 [ERR] plugin: plugin server: accept unix /tmp/plugin870337363: use of closed network connection
2018-12-03T18:35:03.217+0100 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2018/12/03 18:35:03 [ERR] plugin: plugin server: accept unix /tmp/plugin122055116: use of closed network connection
2018-12-03T18:35:03.217+0100 [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2018/12/03 18:35:03 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-12-03T18:35:03.218+0100 [DEBUG] plugin.terraform-provider-rke_v0.6.0_x4: 2018/12/03 18:35:03 [ERR] plugin: plugin server: accept unix /tmp/plugin740034748: use of closed network connection
2018-12-03T18:35:03.219+0100 [DEBUG] plugin: plugin process exited: path=/home/yvespp/build/rancher-infra/clusters/rancher_dev/.terraform/plugins/linux_amd64/terraform-provider-null_v1.0.0_x4
2018-12-03T18:35:03.219+0100 [DEBUG] plugin: plugin process exited: path=/home/yvespp/build/rancher-infra/clusters/rancher_dev/.terraform/plugins/linux_amd64/terraform-provider-template_v1.0.0_x4
2018-12-03T18:35:03.220+0100 [DEBUG] plugin: plugin process exited: path=/home/yvespp/bin/terraform
2018-12-03T18:35:03.220+0100 [DEBUG] plugin: plugin process exited: path=/home/yvespp/build/rancher-infra/clusters/rancher_dev/.terraform/plugins/linux_amd64/terraform-provider-local_v1.1.0_x4
2018-12-03T18:35:03.222+0100 [DEBUG] plugin: plugin process exited: path=/home/yvespp/.terraform.d/plugins/terraform-provider-rke_v0.6.0_x4
2018-12-03T18:35:03.224+0100 [DEBUG] plugin: plugin process exited: path=/home/yvespp/build/rancher-infra/clusters/rancher_dev/.terraform/plugins/linux_amd64/terraform-provider-vsphere_v1.9.0_x4



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Config:
```
provider "rancher2" {
  api_url    = "https://xxx"
  access_key = "xxx"
  secret_key = "xxx"
  ca_certs = "${path.root}/ca.pem"
}

resource "rancher2_auth_config_activedirectory" "activedirectory" {
  servers = ["xxx", "xxx"]
  service_account_username = "xxx"
  service_account_password = "xxx"
  user_search_base = "xxx"
  group_search_base = "xxx"
  username = "xxx"
  password = "xxx"
  port = 389
}
```

**Comment by rawmind0** [comment]
Hi @yvespp . Are you having this issue just with resource `rancher2_auth_config_activedirectory` or with any other?? Which version of terraform are you using?? I can't reproduce issue. 

I suffered similar issue some weeks ago with all tf resources using terraform v0.11.9 until i downloaded terraform binary again.

**Comment by yvespp** [comment]
@rawmind0 I still get a crash with a new terraform. I copy pasted the config above and used that (as is, with the xxx).
I then removed the ca_certs and now it doesn't crash anymore! It doesn't seem to matter if the file exists or not.
```
$ terraform version
Terraform v0.11.10
+ provider.rancher2 v0.1.0-rc1
```

**Comment by rawmind0** [comment]
@yvespp , `ca_certs` parameter is used to save the content of ca certificates not the file name.

**Comment by rawmind0** [comment]
@yvespp, please reopen issue if you need.
